/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.13.2.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { Injectable, InjectionToken } from "@angular/core";

export const API_BASE_URL = new InjectionToken<string>("API_BASE_URL");

@Injectable({
    providedIn: "root"
})
export class ApiClient {
}