version: '3.4'

services:
  webapplication.web:
    build:
      args:
        - EXCLUDE_CLIENT=true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 50001:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  webapplication.webapp:
    image: ${DOCKER_REGISTRY-}webapplicationwebapp
    container_name: WebApplication.WebApp
    build:
      context: ./WebApplication.Web/App
    ports:
      - 50002:4200
      - 50003:49153
    volumes:
      - ./WebApplication.Web/App/src:/app/src
  webapplication.db:
    image: mcr.microsoft.com/mssql/server
    container_name: WebApplication.Db
    ports:
      - 50004:1433
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ${APPDATA}/WebApplication/db/mssql/data:/var/opt/mssql/data